services:
    acme.doctrine.dbal.events.oracle_session_init.listener:
        class: %doctrine.dbal.events.oracle_session_init.class%
        tags:
        - { name: doctrine.event_listener, event: postConnect, connection: oracle }
    acme.doctrine.dbal.oracle_platform.type_mapping.listener:
        class: UTA\SegProBundle\Listener\OracleDoctrineTypeMappingListener
        tags:
        - { name: doctrine.event_listener, event: postConnect, connection: oracle }