UTA\SegProBundle\Entity\Cargo:
  type: entity
  table: cargo
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    cargo:
      type: string
      length: 255
      nullable: false
      column: Cargo
    descripcion:
      type: string
      length: 255
      nullable: false
      column: Descripcion
    role:
      type: string
      lenght: 20
      unique: true
  manyToMany:
    users:
      targetEntity: UTA\SegProBundle\Entity\Usuario
      mappedBy: roles
  lifecycleCallbacks: 
