UTA\SegProBundle\Entity\Estadoproyecto:
  type: entity
  table: estadoproyecto
  id:
    id:
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: AUTO
  fields:
    descripcion:
      type: string
      length: 255
      fixed: false
      nullable: false
      column: Descripcion
  lifecycleCallbacks: {  }