UTA\SegProBundle\Entity\Estadoactividad:
  type: entity
  table: estadoactividad
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    estado:
      type: string
      length: 255
      nullable: false
    descripcion:
      type: string
      length: 255
      nullable: true
  lifecycleCallbacks: 
