UTA\SegProBundle\Entity\Fuentedefinanciamiento:
  type: entity
  table: fuentedefinanciamiento
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    nombre:
      type: string
      length: 255
      nullable: false
      column: Nombre
    descripcion:
      type: string
      length: 255
      nullable: false
      column: Descripcion
    fechaapertura:
      type: date
      nullable: true
      column: FechaApertura
    fechacierre:
      type: date
      nullable: true
      column: FechaCierre
  lifecycleCallbacks: 
