UTA\SegProBundle\Entity\Usuario:
  type: entity
  repositoryClass: UTA\SegProBundle\Entity\UsuarioRepository
  table: usuario
  id:
    id:
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: AUTO
  fields:
    nombre:
      type: string
      length: 255
      fixed: false
      nullable: false
      column: Nombre
    apellido:
      type: string
      length: 255
      fixed: false
      nullable: false
      column: Apellido
#    email:
#      type: string
#      length: 60
#      unique: true
    username:
      type: string
      length: 25
      nullable: false
      unique: true
      column: Usuario
    salt:
      type: string
      length: 32
    password:
      type: string
      length: 255
    isActive:
      type: boolean
      column: is_active
  manyToMany:
    segprouser:
      targetEntity: Segpro
      inversedBy: users
      joinTable:
        name: segpro_usuarios
        joinColumns:
          usuariosid:
            referencedColumnName: id
        inverseJoinColumns:
          segProid:
            referencedColumnName: id
      cascade: [persist, remove]
    roles:
      targetEntity: UTA\SegProBundle\Entity\Cargo
      inversedBy: users
      cascade: [persist, remove]

      
#  oneToOne:
#    cargo:
#      targetEntity: Cargo
#      joinColumn:
#        name: cargo
#        referencedColumnName: id
  lifecycleCallbacks: {  }
