<?php

namespace Proxies\__CG__\UTA\SegProBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Segpro extends \UTA\SegProBundle\Entity\Segpro implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setIdentificador($identificador)
    {
        $this->__load();
        return parent::setIdentificador($identificador);
    }

    public function getIdentificador()
    {
        $this->__load();
        return parent::getIdentificador();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setFuente(\UTA\SegProBundle\Entity\Fuentedefinanciamiento $fuente = NULL)
    {
        $this->__load();
        return parent::setFuente($fuente);
    }

    public function getFuente()
    {
        $this->__load();
        return parent::getFuente();
    }

    public function setFicha(\UTA\SegProBundle\Entity\Fichaproyecto $ficha = NULL)
    {
        $this->__load();
        return parent::setFicha($ficha);
    }

    public function getFicha()
    {
        $this->__load();
        return parent::getFicha();
    }

    public function setActividades(\Doctrine\Common\Collections\Collection $actividads)
    {
        $this->__load();
        return parent::setActividades($actividads);
    }

    public function addActividade(\UTA\SegProBundle\Entity\Actividad $actividades)
    {
        $this->__load();
        return parent::addActividade($actividades);
    }

    public function removeActividade(\UTA\SegProBundle\Entity\Actividad $actividades)
    {
        $this->__load();
        return parent::removeActividade($actividades);
    }

    public function getActividades()
    {
        $this->__load();
        return parent::getActividades();
    }

    public function addUser(\UTA\SegProBundle\Entity\Usuario $users)
    {
        $this->__load();
        return parent::addUser($users);
    }

    public function removeUser(\UTA\SegProBundle\Entity\Usuario $users)
    {
        $this->__load();
        return parent::removeUser($users);
    }

    public function getUsers()
    {
        $this->__load();
        return parent::getUsers();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'identificador', 'nombre', 'fuente', 'ficha', 'actividades', 'users');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}