<?php

namespace Proxies\__CG__\UTA\SegProBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Fichaproyecto extends \UTA\SegProBundle\Entity\Fichaproyecto implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCodigoidentificacion($codigoidentificacion)
    {
        $this->__load();
        return parent::setCodigoidentificacion($codigoidentificacion);
    }

    public function getCodigoidentificacion()
    {
        $this->__load();
        return parent::getCodigoidentificacion();
    }

    public function setNombrecorto($nombrecorto)
    {
        $this->__load();
        return parent::setNombrecorto($nombrecorto);
    }

    public function getNombrecorto()
    {
        $this->__load();
        return parent::getNombrecorto();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setFechainicio($fechainicio)
    {
        $this->__load();
        return parent::setFechainicio($fechainicio);
    }

    public function getFechainicio()
    {
        $this->__load();
        return parent::getFechainicio();
    }

    public function setFechatermino($fechatermino)
    {
        $this->__load();
        return parent::setFechatermino($fechatermino);
    }

    public function getFechatermino()
    {
        $this->__load();
        return parent::getFechatermino();
    }

    public function setFechapostulacion($fechapostulacion)
    {
        $this->__load();
        return parent::setFechapostulacion($fechapostulacion);
    }

    public function getFechapostulacion()
    {
        $this->__load();
        return parent::getFechapostulacion();
    }

    public function setFechaadjudicacion($fechaadjudicacion)
    {
        $this->__load();
        return parent::setFechaadjudicacion($fechaadjudicacion);
    }

    public function getFechaadjudicacion()
    {
        $this->__load();
        return parent::getFechaadjudicacion();
    }

    public function setMontoadjudicado($montoadjudicado)
    {
        $this->__load();
        return parent::setMontoadjudicado($montoadjudicado);
    }

    public function getMontoadjudicado()
    {
        $this->__load();
        return parent::getMontoadjudicado();
    }

    public function setEstadoproyect(\UTA\SegProBundle\Entity\Estadoproyecto $estadoproyect = NULL)
    {
        $this->__load();
        return parent::setEstadoproyect($estadoproyect);
    }

    public function getEstadoproyect()
    {
        $this->__load();
        return parent::getEstadoproyect();
    }

    public function addObjetivo(\UTA\SegProBundle\Entity\Objetivos $objetivos)
    {
        $this->__load();
        return parent::addObjetivo($objetivos);
    }

    public function removeObjetivo(\UTA\SegProBundle\Entity\Objetivos $objetivos)
    {
        $this->__load();
        return parent::removeObjetivo($objetivos);
    }

    public function getObjetivos()
    {
        $this->__load();
        return parent::getObjetivos();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'codigoidentificacion', 'nombrecorto', 'nombre', 'fechainicio', 'fechatermino', 'fechapostulacion', 'fechaadjudicacion', 'montoadjudicado', 'estadoproyect', 'objetivos');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}