admin_fuentedefinanciamiento:
    pattern:  /
    defaults: { _controller: "UTASegProBundle:Fuentedefinanciamiento:index" }

admin_fuentedefinanciamiento_show:
    pattern:  /{id}/show
    defaults: { _controller: "UTASegProBundle:Fuentedefinanciamiento:show" }

admin_fuentedefinanciamiento_new:
    pattern:  /new
    defaults: { _controller: "UTASegProBundle:Fuentedefinanciamiento:new" }

admin_fuentedefinanciamiento_create:
    pattern:  /create
    defaults: { _controller: "UTASegProBundle:Fuentedefinanciamiento:create" }
    requirements: { _method: post }

admin_fuentedefinanciamiento_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "UTASegProBundle:Fuentedefinanciamiento:edit" }

admin_fuentedefinanciamiento_update:
    pattern:  /{id}/update
    defaults: { _controller: "UTASegProBundle:Fuentedefinanciamiento:update" }
    requirements: { _method: post|put }

admin_fuentedefinanciamiento_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "UTASegProBundle:Fuentedefinanciamiento:delete" }
    requirements: { _method: post|delete }
