admin_segpro:
    pattern:  /
    defaults: { _controller: "UTASegProBundle:Segpro:index" }

admin_segpro_show:
    pattern:  /{id}/show
    defaults: { _controller: "UTASegProBundle:Segpro:show" }

admin_segpro_new:
    pattern:  /new
    defaults: { _controller: "UTASegProBundle:Segpro:new" }

admin_segpro_create:
    pattern:  /create
    defaults: { _controller: "UTASegProBundle:Segpro:create" }
    requirements: { _method: post }

admin_segpro_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "UTASegProBundle:Segpro:edit" }

admin_segpro_update:
    pattern:  /{id}/update
    defaults: { _controller: "UTASegProBundle:Segpro:update" }
    requirements: { _method: post|put }

admin_segpro_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "UTASegProBundle:Segpro:delete" }
    requirements: { _method: post|delete }
