<?php

namespace UTA\SegProBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SegproRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SegproRepository extends EntityRepository
{
        public function buscarTodosOrdPorIdentificador()
        {
            return $this->getEntityManager()
                ->createQuery('SELECT p FROM UTASegProBundle:Segpro p ORDER BY p.identificador ASC')
                ->getResult();
        }
    public function buscarAsociadosaUsuario($idUsuario)
    {
        $repository = $this->getEntityManager()->getRepository('UTASegProBundle:Segpro');
        $qb = $repository->createQueryBuilder('p')
//        $qb->select('p')
//           ->from('Segpro','p')
           ->leftJoin('p.users', 'u')
           ->where('u.id = :idUsuario')
           ->setParameter('idUsuario', $idUsuario);
       $proyectos = $qb->getQuery()->execute();
//       \Doctrine\Common\Util\Debug::dump($proyectos);
       return $proyectos;
                
                
                
//        return $this->getEntityManager()
//                ->createQuery('SELECT p FROM UTASegProBundle:Segpro p, UTASegProBundle:Usuario u where u.segprouser = p.id and u.id = :idUsuario ORDER BY p.id ASC')
//                ->setParameter('idUsuario', $idUsuario)
//                    ->getResult();
    }
    
    public function buscarProyectosByYear($year)
    {
        $repository = $this->getEntityManager()->getRepository('UTASegProBundle:Segpro');
        $qb = $repository->createQueryBuilder('p')
//        $qb->select('p')
//           ->from('Segpro','p')
           ->leftJoin('p.ficha', 'f')
           ->andWhere('f.fechainicio >= :year')
           ->setParameter('year', $year);
        
//        $em = $this->getEntityManager();
//        $query = $em->createQuery('SELECT DISTINCT YEAR(FechaInicio) FROM UTASegProBundle:Fichaproyecto');
//        $proyectos = $query->getResult();
       $proyectos = $qb->getQuery()->execute();
//       \Doctrine\Common\Util\Debug::dump($proyectos);
       return $proyectos;
    }

    public function buscarAsociadosaUsuarioByYear($idUsuario, $year)
    {
        $repository = $this->getEntityManager()->getRepository('UTASegProBundle:Segpro');
        $qb = $repository->createQueryBuilder('p')
//        $qb->select('p')
//           ->from('Segpro','p')
           ->leftJoin('p.users', 'u')
           ->leftJoin('p.ficha', 'f')
           ->where('u.id = :idUsuario')
           ->setParameter('idUsuario', $idUsuario)
           ->andWhere('f.fechainicio >= :year')
           ->setParameter('year', $year)
           ->addGroupBy('f.fechainicio')
           ->addOrderBy('f.fechainicio', 'ASC');
       $proyectos = $qb->getQuery()->execute();
//       \Doctrine\Common\Util\Debug::dump($proyectos);
       return $proyectos;
    }
}
