<?php

namespace UTA\SegProBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SegproFuenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SegproFuenteRepository extends EntityRepository
{
    public function getFuentesUso() {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT s from UTASegProBundle:SegproFuente s');
        $fuentes = $query->getResult();
        $result = array();
        foreach ($fuentes as $fuente) {
            if ($fuente->getFuentes()) {
                $result[$fuente->getFuentes()->getId()] = $fuente->getFuentes()->getNombre();
            }
        }
        asort($result);
        
        return $result;
    }
}
